/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bases.view.performance;

import bases.model.Modelo;
import bases.view.admin_tablespaces.menu_admin_tablespaces;
import bases.view.menuprincipal;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CALIL
 */
public class menu_performance extends javax.swing.JFrame {

    /**
     * Creates new form menu_performance
     */
    public menu_performance() throws SQLException {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        comboUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_regresar1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        schema_estadistica = new javax.swing.JComboBox<>();
        tabla_estadistica = new javax.swing.JComboBox<>();
        pass_estadistica = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_crearSchema = new javax.swing.JButton();
        btn_analizarEstadistica = new javax.swing.JButton();
        btn_crearTabla = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_verEstadisticas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Menu para performance de BD");

        btn_regresar1.setText("Regresar");
        btn_regresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresar1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Estadisticas");

        jLabel3.setText("Seleccione el schema:");

        jLabel4.setText("Password:");

        jLabel5.setText("Seleccione la tabla:");

        schema_estadistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schema_estadisticaActionPerformed(evt);
            }
        });

        jLabel6.setText("Estadisticas Schema");

        jLabel7.setText("Estadisticas Tabla");

        jLabel8.setText("Analisis de estadisticas");

        btn_crearSchema.setText("Crear");
        btn_crearSchema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearSchemaActionPerformed(evt);
            }
        });

        btn_analizarEstadistica.setText("Analizar");
        btn_analizarEstadistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_analizarEstadisticaActionPerformed(evt);
            }
        });

        btn_crearTabla.setText("Crear");
        btn_crearTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearTablaActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btn_verEstadisticas.setText("Ver estadisticas");
        btn_verEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verEstadisticasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(814, Short.MAX_VALUE)
                        .addComponent(btn_regresar1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(btn_crearSchema)
                            .addComponent(btn_analizarEstadistica)
                            .addComponent(btn_crearTabla))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tabla_estadistica, 0, 153, Short.MAX_VALUE)
                            .addComponent(schema_estadistica, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pass_estadistica))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_verEstadisticas)
                        .addGap(185, 185, 185))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(schema_estadistica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(pass_estadistica, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(tabla_estadistica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                .addComponent(btn_crearSchema)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addGap(23, 23, 23)
                                .addComponent(btn_crearTabla))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_verEstadisticas)
                        .addGap(7, 7, 7)))
                .addComponent(btn_analizarEstadistica)
                .addGap(39, 39, 39)
                .addComponent(btn_regresar1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresar1ActionPerformed
        // TODO add your handling code here:
        menuprincipal menu = new menuprincipal();
        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_btn_regresar1ActionPerformed

    public  DefaultTableModel modelo1;
    private void btn_verEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verEstadisticasActionPerformed
        // TODO add your handling code here:
        
         Modelo modelo = new Modelo();
        try {
            ResultSet resultados;
            //resultados = modelo.cargarTableSpace();
            
            String tabla = (String) tabla_estadistica.getSelectedItem();
            
            String sql = "SELECT TABLE_NAME, COLUMN_NAME FROM USER_TAB_COL_STATISTICS WHERE table_name = '"+tabla+"'";
            resultados = modelo.consulta(sql);

            modelo1 = new DefaultTableModel();

            jTable1.setModel(modelo1);
            modelo1.addColumn("Table name");
            modelo1.addColumn("Colum Name");
  
            
            if (resultados!=null) {
                    while(resultados.next()){
                     Object dato[]= new Object [2];
                     
                     for (int i=0;i<2;i++){
                         dato[i] = resultados.getObject(i+1);
                     } 
                     modelo1.addRow(dato);
                } 
            } 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(menu_admin_tablespaces.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(menu_admin_tablespaces.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_verEstadisticasActionPerformed

    private void schema_estadisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schema_estadisticaActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            tabla_estadistica.removeAllItems();
            comboTabla();
         } catch (SQLException ex) {
            Logger.getLogger(menu_performance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_schema_estadisticaActionPerformed

    private void btn_crearSchemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearSchemaActionPerformed
        // TODO add your handling code here:
        Modelo modelo = new Modelo();
        
        String schema = (String) schema_estadistica.getSelectedItem();
        
        try {
            modelo.estadisticaSchema(schema);
            JOptionPane.showMessageDialog(null, "Estadistica creada correctamente!");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error al crear la estadistica, intente nuevamente!");
            Logger.getLogger(menu_performance.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_crearSchemaActionPerformed

    private void btn_crearTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearTablaActionPerformed
        // TODO add your handling code here:
        Modelo modelo = new Modelo();
        
        String schema = (String) schema_estadistica.getSelectedItem();
        String tabla = (String) tabla_estadistica.getSelectedItem();
        
        try {
            modelo.estadisticaTabla(schema, tabla);
            JOptionPane.showMessageDialog(null, "Estadistica creada correctamente!");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error al crear la estadistica, intente nuevamente!");
            Logger.getLogger(menu_performance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_crearTablaActionPerformed

    private void btn_analizarEstadisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_analizarEstadisticaActionPerformed
        // TODO add your handling code here:
        Modelo modelo = new Modelo();
        
        String schema = (String) schema_estadistica.getSelectedItem();
        String tabla = (String) tabla_estadistica.getSelectedItem();
        
        try {
            modelo.analizarEstadistica(schema, tabla);
            JOptionPane.showMessageDialog(null, "Estadistica creada correctamente!");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error al crear la estadistica, intente nuevamente!");
            Logger.getLogger(menu_performance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_analizarEstadisticaActionPerformed
    
    public void comboUsuarios () throws SQLException {
    
     Modelo modelo = new Modelo();
    
     String sql ="SELECT USERNAME FROM DBA_USERS";
        try {
            if (modelo.consulta(sql)!=null) {
                ResultSet resultados;
                resultados = modelo.consulta(sql);
                 if (resultados!=null) {
                    while(resultados.next()){
                     Object dato[]= new Object [7];
                      schema_estadistica.addItem(resultados.getString("USERNAME"));
                } 
            } 
                System.out.println(resultados);
            }else{
                System.out.println("Adios mundo");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(menu_performance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void comboTabla() throws SQLException{
    
      Modelo modelo = new Modelo();
    
        String sql ="SELECT TABLE_NAME FROM DBA_TABLES WHERE OWNER = '" + schema_estadistica.getSelectedItem() + "'";
        try {
            if (modelo.consulta(sql)!=null) {
                ResultSet resultados;
                resultados = modelo.consulta(sql);
                 if (resultados!=null) {
                    while(resultados.next()){
                     Object dato[]= new Object [7];
                      tabla_estadistica.addItem(resultados.getString("TABLE_NAME"));
                     /*for (int i=0;i<7;i++){
                         dato[i] = resultados.getObject(i+1);
                        
                     }*/ 

                } 
            } 
                System.out.println(resultados);
            }else{
                System.out.println("Adios mundo");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(menu_performance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_performance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_performance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_performance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_performance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new menu_performance().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(menu_performance.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_analizarEstadistica;
    private javax.swing.JButton btn_crearSchema;
    private javax.swing.JButton btn_crearTabla;
    private javax.swing.JButton btn_regresar1;
    private javax.swing.JButton btn_verEstadisticas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField pass_estadistica;
    private javax.swing.JComboBox<String> schema_estadistica;
    private javax.swing.JComboBox<String> tabla_estadistica;
    // End of variables declaration//GEN-END:variables
}
